image: docker:latest

services:
  - docker:dind

stages:
#- test
- build

variables:
  # The following variables are setup via gitlab project group:
  # DOCKER_HUB_NOTIFY_URL
  # DOCKER_SLUG
  # DOCKER_USERNAME
  # DOCKER_PASSWORD
  # CUSTOM_REGISTRY_URL
  # CUSTOM_REGISTRY_USER
  # CUSTOM_REGISTRY_PW
  # CUSTOM_REGISTRIES
  VERSION: "PLACEHOLDER"


before_script:
- .ci/01_before_install.sh


.build:
  stage: build
  only: 
  - master
  - schedules
  script:
  - make -C .ci build v=$VERSION 
  - make -C .ci tags REPOURL=$CUSTOM_REGISTRY_URL
  - make -C .ci tags REPOURL=$DOCKER_SLUG
  - make -C .ci push REPOURL=$CUSTOM_REGISTRY_URL USER=$CUSTOM_REGISTRY_USER PW=$CUSTOM_REGISTRY_PW
  - make -C .ci push REPOURL=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD
  - make -C .ci notify-hub-docker-com URL=$DOCKER_HUB_NOTIFY_URL

.pull:
  stage: build
  only: 
  - master
  - schedules
  - feat/MDD-169
  script:
  - make -C .ci pull v=$VERSION 
  - make -C .ci tags REPOURL=$CUSTOM_REGISTRY_URL
  - make -C .ci tags REPOURL=$DOCKER_SLUG
  - make -C .ci push REPOURL=$CUSTOM_REGISTRY_URL USER=$CUSTOM_REGISTRY_USER PW=$CUSTOM_REGISTRY_PW
  - make -C .ci push REPOURL=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD
  - make -C .ci notify-hub-docker-com URL=$DOCKER_HUB_NOTIFY_URL


pull-10.4.4-bionic:
    extends: .pull
    variables: 
      VERSION: "library/mariadb:10.4.4-bionic"