stages:
#- test
- build

variables:
  # The following variables are setup via gitlab project group:
  # DOCKER_HUB_NOTIFY_URL
  # DOCKER_SLUG
  # DOCKER_USERNAME
  # DOCKER_PASSWORD
  # CUSTOM_REGISTRY_URL
  # CUSTOM_REGISTRY_USER
  # CUSTOM_REGISTRY_PW
  # CUSTOM_REGISTRIES
  
.build:
  stage: build
  only:
  - master
  - schedules
  - feat/MDD-169
  image:
    # :debug for gitlab-ci sh in image
    name: gitlab.dcso.lolcat:4567/misp/misp-docker-build-container:kaniko_debug
  script:
    - /kaniko/executor --verbosity info
                      --reproducible
                      --digest-file /dev/termination-log 
                      --context "$CI_PROJECT_DIR/$FOLDER"
                      --dockerfile "$CI_PROJECT_DIR/$FOLDER/Dockerfile"
                      --destination "$CUSTOM_REGISTRY_URL/$CI_PROJECT_NAME:$TAG"
                      --destination "$DOCKER_SLUG/$CI_PROJECT_NAME:$TAG"
                      --cache=true
                      --cache-repo="$CI_REGISTRY_IMAGE/cache"
                      --build-arg VCS_REF="$CI_COMMIT_SHA" 
                      --build-arg VERSION="$FOLDER" 
                      --build-arg GIT_REPO="https://github.com/DCSO/$CI_PROJECT_NAME" 
                      --build-arg COMPONENT="db" 
                      --build-arg BUILD_DATE="$(date -u +"%Y-%m-%d")"
    - make -C .ci notify-hub-docker-com URL=$DOCKER_HUB_NOTIFY_URL


build-10.4.4-bionic:
  extends: .build
  variables:
    FOLDER: 10.4.4-bionic
    #TAG: $CI_COMMIT_SHA-$CI_PIPELINE_ID
    TAG: $FOLDER



