stages:
- lint
#- test
- build
- notify

variables:
  # The following variables are setup via gitlab project group:
  # DOCKER_HUB_NOTIFY_URL
  # DOCKER_SLUG
  # DOCKER_USERNAME
  # DOCKER_PASSWORD
  # CUSTOM_REGISTRY_URL
  # CUSTOM_REGISTRY_USER
  # CUSTOM_REGISTRY_PW
  # CUSTOM_REGISTRIES

shellcheck:
  stage: lint
  image: koalaman/shellcheck-alpine
  script:
    - find . -path *.sh -type f -print -exec shellcheck {} +
  allow_failure: true     # If you would check via shellcheck, but not to fail it there is any found.

.build:
  stage: build
  only:
  - master
  - schedules
  - feat/MDD-169
  image:
    # :debug for gitlab-ci sh in image
    name: gitlab.dcso.lolcat:4567/misp/misp-docker-build-container:kaniko_debug
  script:
    - /kaniko/executor --verbosity info
                      --reproducible
                      --digest-file /dev/termination-log 
                      --context "$CI_PROJECT_DIR/$FOLDER"
                      --dockerfile "$CI_PROJECT_DIR/$FOLDER/Dockerfile"
                      --destination "$CUSTOM_REGISTRY_URL/$CI_PROJECT_NAME:$TAG-dev"
                      --destination "$DOCKER_SLUG/$CI_PROJECT_NAME:$TAG-dev"
                      --cache=true
                      --cache-repo="$CI_REGISTRY_IMAGE/cache"
                      --build-arg VCS_REF="$CI_COMMIT_SHA" 
                      --build-arg VERSION="$FOLDER" 
                      --build-arg GIT_REPO="https://github.com/DCSO/$CI_PROJECT_NAME" 
                      --build-arg COMPONENT="db" 
                      --build-arg BUILD_DATE="$(date -u +"%Y-%m-%d")"
    - .ci/05_notify_hub.docker.com.sh $DOCKER_HUB_NOTIFY_URL

notify:
  stage: notify
  image:
    name: appropriate/curl
  script: -X POST -H "Content-Type^^: application/json"  --data '{"docker_tag_name"^^: "hub_automatic_untested"}'  "$NOTIFY_URL"

build-10.4.4-bionic:
  extends: .build
  variables:
    FOLDER: 10.4.4-bionic
    #TAG: $CI_COMMIT_SHA-$CI_PIPELINE_ID
    TAG: $FOLDER



