include:
  - project: 'MISP/helper-containers'
    ref: master
    file: '/.gitlab-ci-template.yml'

stages:
- lint
- build
- notify

build-10.4.4-bionic:
  extends: .build
  variables:
    FOLDER: 10.4.4-bionic
    VERSION: "$FOLDER"
    COMPONENT: db
    TAGS: "${FOLDER}-dev latest-dev"
    #DEBUG: "false"

notify:
  extends: .notify