include:
  - project: 'MISP/helper-containers'
    ref: master
    file: '/.gitlab-ci-template.yml'

stages:
- lint
- build
#- tags
- notify

variables:
  # The following variables are setup via gitlab project group:
  # DOCKER_HUB_NOTIFY_URL
  # DOCKER_SLUG
  # DOCKER_USERNAME
  # DOCKER_PASSWORD
  # CUSTOM_REGISTRY_URL
  # CUSTOM_REGISTRY_USER
  # CUSTOM_REGISTRY_PW
  # CUSTOM_REGISTRIES

.build:
  only:
  - feat/MDD-169

build-10.4.4-bionic:
  extends: .build
  variables:
    FOLDER: 10.4.4-bionic
    VERSION: $FOLDER
    COMPONENT: db
    TAGS: "$FOLDER" latest-dev

notify:
  extends: .notify