language: minimal
dist: xenial
addons:
  apt:
    sources:
      - docker-xenial

env:
  global:
  #- DOCKER_COMPOSE_VERSION=1.4.2
  - COMPONENT="db"

  matrix:
  - FOLDER=10.4.5-bionic

script:
- set -xv
- docker run --rm gcr.io/kaniko-project/executor:debug /kaniko/executor 
                      --verbosity info
                      --reproducible
                      --digest-file /dev/termination-log 
                      --context "$TRAVIS_BUILD_DIR/$FOLDER"
                      --dockerfile "Dockerfile"
                      --no-push
                      --build-arg VCS_REF="$TRAVIS_COMMIT" 
                      --build-arg VERSION="$FOLDER" 
                      --build-arg GIT_REPO="https://github.com/$TRAVIS_REPO_SLUG" 
                      --build-arg COMPONENT="$COMPONENT"
                      --build-arg BUILD_DATE="$(date -u +"%Y-%m-%d")"

# don't notify me when things fail
notifications:
  email: false