language: minimal
dist: xenial
addons:
  apt:
    sources:
      - docker-xenial

env:
  global:
  #- DOCKER_COMPOSE_VERSION=1.4.2
  # The following variables are setup via gitlab project group:
  # - DOCKER_HUB_TOKEN
  # - DOCKER_SLUG
  # - DOCKER_USERNAME
  # - DOCKER_PASSWORD
  # - CUSTOM_REGISTRY_URL
  # - CUSTOM_REGISTRY_USER
  # - CUSTOM_REGISTRY_PWs
  matrix:
  - VERSION=10.4.4-bionic

script:
- docker run --rm gcr.io/kaniko-project/executor:debug /kaniko/executor 
                      --verbosity info
                      --reproducible
                      --digest-file /dev/termination-log 
                      --context "$TRAVIS_BUILD_DIR/$FOLDER"
                      --dockerfile "$TRAVIS_BUILD_DIR/$FOLDER/Dockerfile"
                      --no-push
                      --build-arg VCS_REF="$TRAVIS_COMMIT" 
                      --build-arg VERSION="$FOLDER" 
                      --build-arg GIT_REPO="https://github.com/$TRAVIS_REPO_SLUG" 
                      --build-arg COMPONENT="db"
                      --build-arg BUILD_DATE="$(date -u +"%Y-%m-%d")"

# don't notify me when things fail
notifications:
  email: false